apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: backend-keyvault-secrets
  namespace: default

spec:
  provider: azure

  parameters:
    usePodIdentity: "false"
    clientID: "bec153ce-4266-4705-8dab-6cb77cc95dc5"
    keyvaultName: "mi-ecommerce-app12"
    tenantId: "d7054a45-1c98-4d3f-bc2b-88080bc523e3"

    objects: |
      array:
        - |
          objectName: db-host
          objectType: secret
        - |
          objectName: db-name
          objectType: secret
        - |
          objectName: db-username
          objectType: secret
        - |
          objectName: db-password
          objectType: secret